version: '3'
services:
  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: hellokoding
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  springdatarest-mysql-single:
    build: ./restful-api/springdatarest-mysql-single
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    ports:
    - 8080:8080
    command: bash -c "mvn -N clean install && cd restful-api/springdatarest-mysql-single && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  circular-reference-jackson:
    build: ./restful-api/circular-reference-jackson
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    ports:
    - 8080:8080
    command: bash -c "mvn -N clean install && cd restful-api/circular-reference-jackson && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  springboot-swagger:
    build: ./restful-api/springboot-swagger
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    ports:
    - 8080:8080
    command: bash -c "mvn -N clean install && cd restful-api/springboot-swagger && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  springboot-mockmvc-hsql:
    build: ./restful-api/springboot-mockmvc-hsql
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    ports:
    - 8080:8080
    command: bash -c "mvn -N clean install && cd restful-api/springboot-mockmvc-hsql && mvn clean spring-boot:run"

  springboot-mapstruct:
    build: ./restful-api/springboot-mapstruct
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    ports:
    - 8080:8080
    command: bash -c "mvn -N clean install && cd restful-api/springboot-mapstruct && mvn clean spring-boot:run"
