version: '3'
services:
  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: hellokoding
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  composite-primary-key:
    build: ./jpa-hibernate/composite-primary-key
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/composite-primary-key && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  one-to-one-shared-primary-key:
    build: ./jpa-hibernate/one-to-one-shared-primary-key
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/one-to-one-shared-primary-key && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  one-to-one-foreign-key:
    build: ./jpa-hibernate/one-to-one-foreign-key
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/one-to-one-foreign-key && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  one-to-many:
    build: ./jpa-hibernate/one-to-many
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/one-to-many && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  many-to-many:
    build: ./jpa-hibernate/many-to-many
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/many-to-many && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  many-to-many-extra-columns:
    build: ./jpa-hibernate/many-to-many-extra-columns
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/many-to-many-extra-columns && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  db-migration-flyway:
    build: ./jpa-hibernate/db-migration-flyway
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/db-migration-flyway && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql

  crud-deleting-entity:
    build: ./jpa-hibernate/crud-deleting-entity
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/crud-deleting-entity && mvn clean spring-boot:run"

  crud-querying-entity:
    build: ./jpa-hibernate/crud-querying-entity
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    command: bash -c "mvn -N clean install && cd jpa-hibernate/crud-querying-entity && mvn clean spring-boot:run"
    depends_on:
    - hk-mysql
